In [2]:
import math 
import numpy as np

In [3]:
import math

def basic_sigmoid(x):

  s = 1 / (1 + math.exp(-x))
  return s

In [4]:
basic_sigmoid(2)

0.8807970779778823

In [5]:
import numpy as np

x= np.array([1,2,3])
print(np.exp(x)) #result is (exp(1) (exp(2) (exp(3))))

[ 2.71828183  7.3890561  20.08553692]


In [6]:
x = np.array([1,2,3])
print(x+3)

[4 5 6]


In [7]:
import math
def basic_sigmoid(x):
   s=1/1+np.exp(-x)
   return s
basic_sigmoid(-1)

3.718281828459045

Gradient Function - Sigmoid

In [31]:
def basic_sigmoid(X):

  s=1/(1+np.exp(-X))
  return s

In [10]:
def basic_sigmoid(x):
    
    s=1/(1+np.exp(x))
    return s

In [11]:
def sigmoid_derivative(x):

  s = 1/(1+np.exp(-x))
  ds = s*(1-s)
  return ds

In [13]:
  x= np.array([1,2,6])
  print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))
  

sigmoid_derivative(x) = [0.19661193 0.10499359 0.00246651]


Reshaping Arrays (3D image to 1D)

In [35]:
import numpy as np

image = np.array([[[0.67826139, 0.29380381],
                   [0.90714982, 0.52835647],
                   [0.4215251, 0.45017551]],
                  
                  [[0.92814219, 0.96677647],
                   [0.85304703, 0.52351845],
                   [0.19981397, 0.27417313]],
                  
                  [[0.60659855, 0.00533165],
                   [0.10820313, 0.49978937],
                   [0.34144279, 0.94630077]]])

def image2vector(image):
    return image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))

print("image2vector(image) = " + str(image2vector(image)))

note - #str(image2vector(image))) - this is not a function from library.

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


Gradient Function - normalisation

In [36]:
def noramlizeRows(x):
  """
  Implement a function that normalizes each row of the matrix x (to have unit length).

  Argument:
  x -- A numpy matrix of shape (n, m)

  Returns:
  x -- The normalized (by row) numpy matrix. You
  """
  x_norm = np.linalg.norm(x,axis=1,keepdims=True)
  x = x/x_norm
  return x

In [37]:
x = np.array([[0,1000,40],
             [2,6,4]])
print("noramlizeRows(x) = " + str(noramlizeRows(x)))

noramlizeRows(x) = [[0.         0.99920096 0.03996804]
 [0.26726124 0.80178373 0.53452248]]


Gradient Function - Softmax

In [14]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum    
    return s

In [15]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print(softmax(x))

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


VECTORIZATION

In [41]:
import time

x1 = [9,2,5,0,0,7,5,0,0,9,2,5,0,0]
x2 = [9,2,2,9,0,9,2,5,0,0,9,2,5,0]
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()

print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

###vectorized outer product
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i,j] = x1[i]*x2[j]
    toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

###classic elementwise implementation
tic = time.process_time()
ele = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    ele[i,j] = x1[i]*x2[j]
    toc = time.process_time()
print ("elementwise = " + str(ele) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 196
 ----- Computation time = 0.0ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ----- Computation time = 15.625ms
elementwise = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.]
 [18.  4.  4. 1

Calculating time taken with 1000

In [42]:
import time
import numpy as np

x1 = np.random.rand(1000)
x2 = np.random.rand(1000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()

print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 252.97352514336168
 ----- Computation time = 0.0ms


Calculating time taken with more than 1000 

In [43]:
import time
import numpy as np

x1 = np.random.rand(10000000)
x2 = np.random.rand(10000000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()

print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 2500250.3675005115
 ----- Computation time = 9500.0ms


NOTE- Calculating time taken with more than 10000000 will throw an error as session crashed

Implimenting L1 and L2 as Loss function.

In [ ]:
def L1(yhat,y):
  loss=np.sum(np.abs(y-yhat))
  return loss

yhat=np.array([1,1,1,1,1])
y=np.array([1,1,1,1,1])
print("L1="+str(L1(yhat,y)))